### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mhsjlw** [gkbrk/RustOre-Classic#3]
Since this project seems unmaintained, I've updated my own fork of it, but I'm curious as to what the license is. Is it the standard MIT, Apache 2.0 or public domain?

**Comment by gkbrk** [comment]
Yeah, this project is unmaintained for the time being. It was a project for learning Rust but I might rewrite or update it one day.

I added a license (MIT). Here's the [LICENSE file](https://github.com/gkbrk/RustOre-Classic/blob/master/LICENSE) you need include with your project.

**Comment by ghost** [comment]
Awesome, thanks.
